//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.0.3+a0f3c15
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace elastic.Web.Models
{
	/// <summary>Logo Settings</summary>
	[PublishedModel("LogoSettingsModel")]
	public partial class LogoSettingsModel : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		public new const string ModelTypeAlias = "LogoSettingsModel";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<LogoSettingsModel, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public LogoSettingsModel(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// #BackOffice.Settings.LogoSettings.AlternateText: #BackOffice.Settings.LogoSettings.AlternateText.Hint
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("LogoSettingsAlternateText")]
		public virtual string LogoSettingsAlternateText => this.Value<string>(_publishedValueFallback, "LogoSettingsAlternateText");

		///<summary>
		/// #BackOffice.Settings.LogoSettings.DesktopLogo: #BackOffice.Settings.LogoSettings.DesktopLogo.Hint
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("LogoSettingsDesktop")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LogoSettingsDesktop => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "LogoSettingsDesktop");

		///<summary>
		/// #BackOffice.Settings.LogoSettings.DesktopLogo.White: #BackOffice.Settings.LogoSettings.DesktopLogo.White.Hint
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("LogoSettingsDesktopWhite")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LogoSettingsDesktopWhite => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "LogoSettingsDesktopWhite");

		///<summary>
		/// #BackOffice.Settings.LogoSettings.Link: #BackOffice.Settings.LogoSettings.Link.Hint
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("LogoSettingsLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link LogoSettingsLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "LogoSettingsLink");

		///<summary>
		/// #BackOffice.Settings.LogoSettings.MobileLogo: #BackOffice.Settings.LogoSettings.MobileLogo.Hint
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("LogoSettingsMobile")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LogoSettingsMobile => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "LogoSettingsMobile");

		///<summary>
		/// #BackOffice.Settings.LogoSettings.MobileLogo.White: #BackOffice.Settings.LogoSettings.MobileLogo.White.Hint
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.0.3+a0f3c15")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("LogoSettingsMobileWhite")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LogoSettingsMobileWhite => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "LogoSettingsMobileWhite");
	}
}
